Added connections between components
loriot/AzureSolutionTemplate pull request #22
Opened 2017-10-13 13:11 UTC by Mandur

- connection with router Function
- Setup function triggered from template at deploy time
- SQL & DocDB get populated by the same setup function

Took ARM part for SQL/DocDB from Anita-dev

2017-10-13 16:14 UTC, Mandur commented
If you test this PR, make sure to edit the current GitHub code branch in the azuredeploy.json otherwise the Setup function will fail miserably

2017-10-17 10:32 UTC, vjrantal requested changes

2017-10-17 10:32 UTC, vjrantal commented on src/LoriotAzureFunctions/Route/RouteFunction.cs
> +                        await Task.Delay(5000);
The default delay could be something like 1 second that should be enough to avoid the original problem.

2017-10-17 11:04 UTC, Mandur commented
PR has been updated with the new timer value

2017-10-17 11:05 UTC, merged